### ISSUE TITLE
SourceForge Project not found

### ISSUE THREAD

**Issue by JLabisch** [drventure/Disambiguator#1]
Sorry if that's not the appropriate place to report, but I found no other.

Because the link provided in the readme and the documentation here,  <http://sourceforge.net/projects/disambiguator>, where the bugtracker and forum is promised,  leads to "Page not found".

**Comment by drventure** [comment]
Oh wow. I completely missed that sourceforge link in the readme.

Sorry for the confusion.

You're in the right place here. This Github page is really the official repo of the project.
