### ISSUE TITLE
Copy to clipboard button does not work in Report window

### ISSUE THREAD

**Issue by bege10** [drventure/Disambiguator#10]
Clicking the button does nothing. I must select the text and copy with context menu or CTRL+C.

**Comment by drventure** [comment]
Thanks. I'll check on that.

**Comment by drventure** [comment]
I had a look at this. It's a pretty simple routine and it should either "beep" if it successfully posts the report to the clipboard or play the "exclamation" sound if it fails. It could fail if another application has locked the clipboard for whatever reason, but that's usually a pretty rare occurrence.

**Comment by bege10** [comment]
I was not precise enough. The system error sound can be heard.
What is different what the button does from the right-click menu copy function, which works?
As this does not happen with any other app, what kind of application might lock the clipboard? I stopped the multi clipboard app Ditto and removed the clipboard related security settings in KeePass - nothing helps.
But if I can copy with right-click menu the clipboard cannot be locked?

**Comment by drventure** [comment]
Should be fixed in the latest version.

**Comment by drventure** [comment]
Thank you!
