### ISSUE TITLE
Slow auto-type performance after latest update

### ISSUE THREAD

**Issue by Noctudeit** [drventure/Disambiguator#5]
There has been a significant delay (5-10 seconds) any time I initiate auto-type after updating to 1.0.2.0. This delay occurs both using the global auto-type shortcut as well as using auto-type from within KeePass. I rolled back Disambiguator to 1.0.1.0 and the delay went away.

**Comment by drventure** [comment]
Sorry to hear that.

The 1.0.2 version has built in logging that might help.

To turn it on, drop down the TOOLS menu, and choose "The Disambiguator Options", then "Logging"

This will turn ON logging, repeat the process to turn it off. If you restart Keepass, it will automatically be turned off.

The log is written to the current user's desktop. No passwords or identifying info is written to the log file, but the details of what   is scanned is, and that often helps in resolving issues like this.

the log file is plain text, so feel free to look it over.

If you're comfortable sending it to me, feel free to do so and I can have a look.

If not, that's ok. Read through it, looking for any significant delays between lines (noting the time on each line).

If any one particular entry shows to incur a significant delay, let me know that app it was interrogating at that point (or copy just those few lines from the log file and attach them here.)

If you don't mind me asking, would you know about how many entries you have in your keepass DB?
I have about 700 entries in mine and usually see between a second and 2 seconds delay when I hit the hotkey.

To find a total, I just perform a find with an empty search term. Keepass will show the find results with the total count at the bottom.

**Comment by newboydj169** [comment]
hi 
I have a case and more seriously. It delay 10 mins.
I think the first sevral lines should represent the problem already.
Kindly pls take a look:

6/28/2023 8:09:56 PM Sequence Queries Begin
6/28/2023 8:09:56 PM Traversing Control Tree...
6/28/2023 8:19:16 PM ResolveSequence for AutoType Sequence Title
6/28/2023 8:19:16 PM ResolveSequence winName=家用QQ  sequence={USERNAME}{TAB}{PASSWORD}{ENTER}  eventId=2  TargetTitle=登录 — Mozilla Firefox  TargetHandle=789198


all my software is the latest version to the report date.

**Comment by drventure** [comment]
Wow. Ok. Thank you for taking the time to grab the log and post.
It definitely looks like there's something going on in the control tree
traversal. I've never had it take 10 minutes like that on anything and I
use KeepPass for tons of apps as well as websites.

This gives me something definite to investigate though.

I'll post more once I've had a chance to do some digging.

Thanks again!

**Comment by drventure** [comment]
I'm just posted build 1.0.3 which should address the issue with slowness during autotype in some target apps.
Feel free to try it out and let me know.
If you're still seeing slowness, it'd be great if you could turn logging on, perform the autotype and post the log (or just a relevant clip of it).

**Comment by drventure** [comment]
You might notice a 1.0.4 release now up. There's really very little change between 1.0.3 and 1.0.4, Just FYI

**Comment by drventure** [comment]
I'm closing this out now, because I was able to replicate the issue, so at this point, I'm fairly certain 1.0.3 and 1.0.4 will resolve it.
