### ISSUE TITLE
DisambiguatorExt.TraverseControlTree

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [drventure/Disambiguator#7]
The Disambiguator 1.0.5.0 Got error:
```

`---------------------------

---------------------------
An error was encountered:

System.ArgumentException: hwnd darf nicht IntPtr.Zero oder NULL sein.

   bei System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)

   bei Disambiguator.DisambiguatorExt.TraverseControlTree(IntPtr targetWindowHandle, Int32 depth)
---------------------------
OK   
---------------------------
`
```

**Comment by drventure** [comment]
Hmm, Normally, when invoked, Keepass gets a Window Handle of the "active" window, and then starts the process of determining which entries might apply to that window. The disambiguator hooks into that process and digs a little deeper into the target window to look for additional clues to more accurately identify the window.

Looks like Keepass sent a window handle to Disambiguator that was null, which normally shouldn't happen. 

Is it possible that the target window was somehow closed before Keepass had a chance to send keystrokes to it?

Does this consistently happen or does it work most of the time?

What application are you sending keystrokes to?

and finally, does this only occur against that specific application or does it happen all the time, or to other applications?

**Comment by drventure** [comment]
No Response. Closing issue. Please feel free to reopen or let me know.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
![TraverseControlTree](https://github.com/user-attachments/assets/45fa0fc9-1f37-4b0a-a847-cc7d48535e34)

The error occurred again today. Disambiguator v1.0.7.0 KeePass 2.57.1

> Is it possible that the target window was somehow closed before Keepass had a chance to send keystrokes to it?

This time, I remember the window with password field, where I pressed the Autotype hotkey, remained open. 
The Database state was locked before triggering.

> 
> Does this consistently happen or does it work most of the time?

Only happens very rarely, noticed this just two times in about 3 years daily usage.

**Comment by drventure** [comment]
Very strange. In this particular case, Keepass is actually passing the addin a traget window handle that's null.
Not sure why it'd do that unless the target window was somehow closed or... I don't know.

Anyway, I'm going to update Disambiguator to check for that condition and avoid the error. IF the target window handle is null, there's nothing that Disambiguator can do anyway.

**Comment by drventure** [comment]
The v1.0.9 build should resolve this issue.
