### ISSUE TITLE
Random error popups when using auto-fill

### ISSUE THREAD

**Issue by bege10** [drventure/Disambiguator#8]
I use KeePass 2.57 with Disambiguator 1.0.5.0 and Firefox 130.0 on Windows 11 Professional 64 bit 23H2. Randomly when I use the Ctrl+Alt+A hotkey for KeePass auto-type I get this error popup . This happens not on every site and on affected sites not always. I did not find out a pattern yet. After clicking OK sometimes nevertheless the auto-type popup opens correctly, but sometimes nothing happens.
The message says that the target element is not available any more. But this is not the case, especially when the auto-type popup shows up after the message.
The KeePass developer wrote that this is an issue of Disambiguator and recommended to report the issue here.

![Screenshot_358](https://github.com/user-attachments/assets/b9f33d6e-20cc-4ce7-8d48-9c18e49f39c5)

**Comment by drventure** [comment]
Hi, Yes, would definitely be a Disambiguator issue.
It was my understanding that when using the MSAA (Microsoft accessibility layer), that every UI element would always have "Name", "ClassName", and "AutomationID" properties.

Appearently, in some situations that isn't the case :)

Based on the screenshot, it looks like the "Name" property may or may not be defined for a particular UI Element.

That would explain why it appears only occasionally.

I'll have a look. Haven't had any reports of this before, so I may be related to running in a different language. However, generally, with the MSAA stuff, that's not a problem.

Thanks for the report. I'll get back to you with here with what I find.

**Comment by drventure** [comment]
This issue should be resolved now. I've posted an update v1.0.6.0 that, essentially, just ignores those cases where any of the MSAA properties can't be enumerated. I was under the impression that they all HAD to return something, but that appears to not be the case.

**Comment by bege10** [comment]
Thank you. I will test and come back here later.

**Comment by drventure** [comment]
Hi Just thought I'd check back in with you and see if that helped resolve your issue... Let me know if I can help.

**Comment by bege10** [comment]
Sorry for not giving feedback. I forgot this over the other issues. Yes the issue did not happen again. Thank you very much.
